// Build-specific effect descriptions from the local ORIGINAL English column.
// Only explicitly reviewed unconditional contributions have a numeric value.
internal sealed record LscEffect(string Name, string Description, double? Flat, double? Cap);
internal static class LscCatalog
{
    internal static readonly Dictionary<(string Source, int Id, int Level), LscEffect> Entries = new()
    {
        [("ascension", 2035, 1)] = new("Lucky Ammo", "+20% to Lucky Shot Chance while dual-wielding", null, null),
        [("ascension", 2035, 2)] = new("Lucky Ammo", "+30% to Lucky Shot Chance while dual-wielding", null, null),
        [("ascension", 2035, 3)] = new("Lucky Ammo", "+40% Lucky Shot Chance while dual-wielding. When triggering a crit hit and a lucky shot simultaneously, gain an additional +20% Lucky Shot Chance for 1s.", null, null),
        [("ascension", 2041, 1)] = new("Unleashed Potential", "During Dual-Wielding, gain +3% Weapon DMG and +1% lucky shot chance every 0.5s with continuous firing (up to 20 stacks). \\nLose 5 stacks every 0.5s when not firing.", null, null),
        [("ascension", 2216, 1)] = new("Hail of Bullets", "+30% weapon DMG and +20% Lucky Shot chance when the magazine is full . The first 3 shots after reloading consume no ammo.", null, null),
        [("ascension", 2216, 2)] = new("Hail of Bullets", "+60% weapon DMG and +30% Lucky Shot chance when the magazine is full . The first 4 shots after reloading consume no ammo.", null, null),
        [("ascension", 2216, 3)] = new("Hail of Bullets", "+100% weapon DMG and +40% Lucky Shot chance when the magazine is full . The first 5 shots after reloading consume no ammo.", null, null),
        [("ascension", 2714, 3)] = new("Sword Enthusiast", "For every flying sword summoned, increase weapon DMG and skill DMG by 4% and lucky shot chance by 2% for 10s", null, null),
        [("ascension", 3107, 1)] = new("Burning Bullet", "When hitting an enemy, if energy is more than 50%, consume 6 energy for +30% Lucky Shot Chance; or recover 15 energy (CD: 5s)", null, null),
        [("ascension", 3107, 2)] = new("Burning Bullet", "When hitting an enemy, if energy is more than 50%, consume 8 energy for +50% Lucky Shot Chance; or recover 25 energy (CD: 5s)", null, null),
        [("ascension", 3107, 3)] = new("Burning Bullet", "When hitting an enemy, if energy is more than 50%, consume 10 energy for +70% Lucky Shot Chance; or recover 35 energy (CD: 5s)", null, null),
        [("ascension", 3110, 1)] = new("Flame Forged", "For every 60 energy cap, +50% Elemental Effect Chance of current weapon. For every 1% Elemental Effect Chance, +1.5% current Weapon DMG (Up to 150%); when Elemental Effect Chance >100%, every 10% over the limit grants +5% Lucky Shot Chance", null, null),
        [("ascension", 3214, 1)] = new("Last Star", "When consuming the last ammo in the magazine, clear 1 random [Astroaspect] and +15% Lucky Shot Chance for 3s.", null, null),
        [("ascension", 3214, 2)] = new("Last Star", "When consuming the last ammo in the magazine, clear 1 random [Astroaspect] and +20% Lucky Shot Chance for 4s.", null, null),
        [("ascension", 3214, 3)] = new("Last Star", "When consuming the last ammo in the magazine, clear all [Astroaspects], +25% Lucky Shot Chance for 4s for every [Astroaspects]. If it's [Wild Astroaspects], the bonus effect doubles.", null, null),
        [("ascension", 3215, 2)] = new("Bet It All", "When clearing slots, +10% Base Weapon DMG for every slot for 7s, different [Astroaspects] provide different bonuses, up to 6 stacks. <color=#6BDCDC>[Normal Astroaspect]</color>: +10% Base DMG. <color=#B56EEA>[Rare Astroaspect]</color> or <color=#E4A747>[Legendary Astroaspect]</color>: +10% Lucky Shot Chance. <color=#CC000A>[Wild Astroaspect]</color>: Obtain a random bonus", null, null),
        [("ascension", 3215, 3)] = new("Bet It All", "When clearing slots, +15% Base Weapon DMG for every slot for 8s, different [Astroaspects] provide different bonuses, up to 8 stacks. <color=#6BDCDC>[Normal Astroaspect]</color>: +15% Base DMG. <color=#B56EEA>[Rare Astroaspect]</color>: +15% Lucky Shot Chance. <color=#E4A747>[Legendary Astroaspect]</color>: +0.3x Weapon CritX. <color=#CC000A>[Wild Astroaspect]</color>: Obtain a random bonus, and there is a chance to obtain all bonuses", null, null),
        [("ascension", 3315, 1)] = new("Lucky Break", "+20% Lucky Shot Chance on Pistol Critical. Triggering Lucky Shot causes bullets to ricochet, dealing 8% DMG per hit. Max 2/4 ricochets for 2x/3x CritX", null, null),
        [("ascension", 3315, 2)] = new("Lucky Break", "+40% Lucky Shot Chance on Pistol Critical. Triggering Lucky Shot causes bullets to ricochet, dealing 10% DMG per hit. Max 3/5 ricochets for 2x/3x CritX", null, null),
        [("ascension", 3315, 3)] = new("Lucky Break", "When Pistol lands a Critical, +60% Lucky Shot Chance for 3s. When a Lucky Shot is triggered, the bullet ricochets, dealing 12% DMG per hit. If the Lucky Shot deals 2x/3x/4x DMG, it ricochets up to 4/6/9 times.", null, null),
        [("ascension", 3614, 1)] = new("Geometry Art", "When enemies are within 8 meters, +60% weapon DMG; When enemies are beyond 8 meters, +30% Lucky Shot chance. Apply both effects when staying in [Blank Domain]", null, null),
        [("ascension", 3614, 2)] = new("Geometry Art", "When enemies are within 8 meters, +90% weapon DMG; When enemies are beyond 8 meters, +45% Lucky Shot chance. Apply both effects when staying in [Blank Domain]. Weapon will have a 20% Chance to deal DMG once more", null, null),
        [("ascension", 3614, 3)] = new("Geometry Art", "When enemies are within 8 meters, +120% weapon DMG; When enemies are beyond 8 meters, +60% Lucky Shot chance. Apply both effects when staying in [Blank Domain] or maintaining [Ink Shade]. Weapon will have a 30% Chance to deal DMG once more", null, null),
        [("ascension", 3615, 2)] = new("Grinding Ink", "+80% DMG for 6s after using a weapon skill. Gain 1 stack for every 9s (up to 3 stacks). When weapon skill resource is below 33%, cost 2 stacks to fully restore weapon skill resources. +40% Lucky Shot chance if the stack is over 2", null, null),
        [("ascension", 3615, 3)] = new("Grinding Ink", "+120% DMG for 6s after using a weapon skill. Gain 1 stack for every 9s or cost 300% weapon skill resource (up to 3 stacks). Cost 2 stacks to fully restore weapon skill resource, +60% Lucky Shot chance if the stack is over 2", null, null),
        [("ascension", 3713, 1)] = new("Profound Shadow", "+20% Lucky Shot Chance when hitting Shadowbind; +10% extra per 1s Shadowbind lasts (max +40%)", null, null),
        [("ascension", 3713, 2)] = new("Profound Shadow", "+40% Lucky Shot Chance when hitting Shadowbind; +20% extra per 1s Shadowbind lasts (max +60%)", null, null),
        [("ascension", 3713, 3)] = new("Profound Shadow", "+60% Lucky Shot Chance when shooting [Shadowbind]. +40% per 1s [Shadowbind] lasts (max +80%)", null, null),
        [("ascension", 3815, 1)] = new("Energy Recall", "+2% Weapon Skill Lucky Shot Chance and 1% chance to deal 1 extra hit per 1 Weapon Skill resource max on main Weapon", null, null),
        [("ascension", 3815, 2)] = new("Energy Recall", "+4% Weapon Skill Lucky Shot Chance and 2% chance to deal 1 extra hit per 1 Weapon Skill resource max on main Weapon", null, null),
        [("ascension", 3815, 3)] = new("Energy Recall", "+8% Weapon Skill Lucky Shot Chance and 3% chance to deal 1 extra hit per 1 Weapon Skill resource max on main Weapon", null, null),
        [("ascension", 5027, 1)] = new("Combined Arms", "Mecha Drop taunts enemies within 10m of Nona. Enemies within 10m of Iron Wing and taunted enemies are Pinged exposing weak points. Nona deals +200% Weapon DMG and +100% Lucky Shot Chance to Pinged enemies. Nona can remotely revive Iron Wing instantly with 60s CD. CD -1s per Lucky Shot triggered", null, null),
        [("ascension", 5028, 1)] = new("No Pain No Gain", "Obtain a <color=#B56EEA>[Rare Astrohouse]</color> when using [Falling Star] after dealing Crit Hits/Lucky Shots 20 times, or a <color=#E4A747>[Legendary Astrohouse]</color> after dealing Crit Hits/Lucky Shots 40 times. Accumulated Crit Hits/Lucky Shots reset after using [Falling Star].", null, null),
        [("ascension", 5205, 1)] = new("Well-trained", "When attacking with a weapon, +2x CritX if the enemy is in Elemental Effect; +75% Lucky Shot Chance if not.", null, null),
        [("blessing", 13502, 1)] = new("Weapon Genius", "-50% Dual-Wield cooldown. +75% Lucky Shot Chance, and Weapon 1 & 2 share their highest weapon level while Dual-Wielding.", null, null),
        [("blessing", 13532, 1)] = new("Primordial Unity", "[Qi] capacity doubled; +1 [Qi] stack per 4s; +5% Lucky Shot Chance per Main Weapon Level. While [Qi] stacks are above 50% of maximum, gain benefits equal to max stacks", null, null),
        [("blessing", 13542, 1)] = new("Same Boat", "30% of the DMG taken by Nona is shared to Iron Wing. Iron Wing marks enemies on hit. Nona: +3x CritX, +250% Weapon DMG, +50% Lucky Shot Chance when hit marked enemies by weapon. Iron Wing heals 10%/5% HP when attacking same enemy as Nona in Strike Mode/ Fire Mode", null, null),
        [("blessing", 13545, 1)] = new("Functional Deck", "+50% Weapon DMG for 5s when consuming [Astroaspects], up to 300%. Every 6 [Astroaspects] consumed allows drawing a card with different effects for 10s. Each card effect stacks up to 3. <color=#6BDCDC>Blue Card</color>: +40% Lucky Shot Chance; <color=#B56EEA>Purple Card</color>: +30% RoF; <color=#E4A747>Orange Card</color>: +40% Movement Speed, 40% chance for projectile+1 when shooting; <color=#CC000A>Red Card</color>: Obtain all card effects", null, null),
        [("blessing", 13706, 1)] = new("Field Proficiency", "+10% Lucky Shot Chance, -6% Dash/Primary Skill cooldown, for every elite/boss killed or assisted on kill in the entire run, up to 10 stacks. (Including enemies before obtaining this spiritual blessing)", null, null),
        [("blessing", 13721, 1)] = new("Skilled Trick", "Every time you use the Weapon Skill, +20% Lucky Shot Chance for 10s (up to 10 stacks).", null, null),
        [("gem", 51762, 1)] = new("Lucky Shot", "+12% Lucky Shot Chance; +6% Lucky Shot Chance per 10 Soul Pendant energy cost for 5s", 12, null),
        [("gem", 51762, 2)] = new("Lucky Shot", "+18% Lucky Shot Chance; +9% Lucky Shot Chance per 10 Soul Pendant energy cost for 5s", 18, null),
        [("gem", 51762, 3)] = new("Lucky Shot", "+27% Lucky Shot Chance; +15% Lucky Shot Chance per 10 Soul Pendant energy cost for 5s", 27, null),
        [("gem", 51779, 1)] = new("Lucky Charge", "Restore Soul Pendant Energy equal to Lucky Shot multiplier on Lucky Shot, 4s CD", null, null),
        [("gem", 51779, 2)] = new("Lucky Charge", "Restore Soul Pendant Energy equal to Lucky Shot multiplier on Lucky Shot, 3s CD", null, null),
        [("gem", 51779, 3)] = new("Lucky Charge", "Restore Soul Pendant Energy equal to Lucky Shot multiplier on Lucky Shot, 2s CD", null, null),
        [("scroll", 5730, 1)] = new("Ninja's Discipline", "+30 stacks every 3s. +0.5%Lucky Shot chance for each stack (up to 90 stacks). -10 stacks after dealing Weapon DMG", null, null),
        [("scroll", 5730, 2)] = new("Ninja's Discipline", "+30 stacks every 3s. +0.5%Lucky Shot chance for each stack (up to 120 stacks). -8 stacks after dealing Weapon DMG", null, null),
        [("scroll", 5756, 1)] = new("Coin Shot", "+30% Lucky Shot Chance by consuming 2 copper when you land a shot. Copper spent will be refunded if you successfully trigger a Lucky Shot.", null, null),
        [("scroll", 5756, 2)] = new("Coin Shot", "Consume two coins on each hit with +60% total weapon DMG (Can't be triggered when you don't have any copper). Killing an enemy in 5 hits refunds all Copper spent on the enemy. Triggering a Crit Hit/Lucky Shot/Elemental Effect does not consume any copper.", null, null),
        [("scroll", 5767, 1)] = new("Casual Gunsmanship", "+20% Lucky Shot Chance, but -20% weapon DMG when you don't make a Lucky Shot.", 20, null),
        [("scroll", 5767, 2)] = new("Casual Gunsmanship", "+20% Lucky Shot Chance, and there is still a 20% chance to inflict a crit hit if you don't hit weaknesses.", 20, null),
        [("scroll", 5768, 1)] = new("Elemental Torment", "+20% Lucky Shot Chance against enemies affected by Elemental Effect", null, null),
        [("scroll", 5768, 2)] = new("Elemental Torment", "+20% Lucky Shot Chance against enemies under an elemental effect; There's a 20% chance to apply an elemental effect when hitting an enemy not affected by any elemental effect.", null, null),
        [("scroll", 5770, 1)] = new("Speedy Pursuit", "+50% Lucky Shot Chance for 2s after dashing.", null, null),
        [("scroll", 5770, 2)] = new("Speedy Pursuit", "+50% Lucky Shot Chance for 2s after dashing; -1s Dash cooldown after inflicting a lucky shot.", null, null),
        [("scroll", 5771, 1)] = new("Berserk Soul", "+0.5% Lucky Shot Chance for each 1% HP missing", null, null),
        [("scroll", 5771, 2)] = new("Berserk Soul", "+1% Lucky Shot Chance for every 1% total HP missing.", null, null),
        [("scroll", 5772, 1)] = new("Merciless Strike", "+50% Lucky Shot Chance on Crit Hit, -50% Lucky Shot Chance on Normal Hit.", null, null),
        [("scroll", 5772, 2)] = new("Merciless Strike", "+50% Lucky Shot Chance on a Crit Hit; +0.5x CritX on a Lucky Shot.", null, null),
        [("scroll", 5785, 2)] = new("Evil-Devouring Sword", "For every cursed scroll you own, +40% Weapon DMG and Skill DMG, +20% Lucky Shot Chance.", null, null),
        [("scroll", 5792, 1)] = new("Fast-Loader", "After swapping weapons, replenish the magazine instantly and +30% Lucky Shot Chance. (Gradually decreases to 0% over 3s)", null, null),
        [("scroll", 5792, 2)] = new("Fast-Loader", "Fill the magazine instantly after swapping weapons. +30% Lucky Shot Chance (Gradually decreases to 0% over 3s), and your first 3 shots won't consume ammo.", null, null),
        [("scroll", 5815, 1)] = new("Lone Ranger", "When not within 12m of a monster, gain +1% Lucky Shot chance every 0.5s (up to 20 stacks). Lose 1 stack every 0.5s when within 12m of a monster. When at 20 stacks, gain an additional 5% Lucky Shot chance.", null, null),
        [("scroll", 5815, 2)] = new("Lone Ranger", "When there are no monsters within 8 meters, gain 2 stacks every 0.5s (up to 40 stacks). Lose 1 stack every 0.5s otherwise. Gain +1% Lucky Shot Chance per stack, and when at 40 stacks, gain an additional 10% Lucky Shot Chance.", null, null),
        [("scroll", 5817, 1)] = new("Bullet Light", "+25% Lucky Shot Chance for each shot at the cost of 1 additional spare ammo. Recover consumed spare ammo upon triggering a lucky shot.", null, null),
        [("scroll", 5817, 2)] = new("Bullet Light", "+25% Lucky Shot Chance. Recover one consumed ammo to magazine and reserve upon triggering a lucky shot.", 25, null),
        [("scroll", 5824, 1)] = new("Good and Evil", "+15% Lucky shot chance if you don't own any cursed scroll; +15 max shield/armor for each cursed scroll you own", null, null),
        [("scroll", 5824, 2)] = new("Good and Evil", "+30% Lucky Shot Chance and -30% Dash/Primary Skill cooldown if you don't own any cursed scrolls; +15 max HP and max Shield/Armor for each cursed scroll you own.", null, null),
        [("scroll", 5828, 2)] = new("Elemental Magazine", "Deals an additional 50% DMG when Weapon DMG causes an elemental effect/Crit Hit/Lucky Shot.", null, null),
        [("scroll", 5829, 1)] = new("Reasonable Luck", "+80% Lucky Shot Chance, but total Lucky Shot Chance won't exceed 150%.", 80, 150),
        [("scroll", 5829, 2)] = new("Reasonable Luck", "+80% Lucky Shot Chance.", 80, null),
        [("scroll", 5852, 2)] = new("Normal Ammo", "-100% extra ammo of other types when shooting with normal ammo weapons. +30% Weapon DMG for each extra ammo consumed in this shooting, +30% chance of a lucky shot for every large ammo consumed, +0.5x CritX for every special ammo consumed.", null, null),
        [("scroll", 5853, 2)] = new("Large Ammo", "-200% extra special ammo when shooting with large ammo weapons.  +30% Lucky Shot Chance for each large ammo consumed in this shooting, +0.5x CritX for every special ammo consumed.", null, null),
        [("scroll", 5854, 1)] = new("Special Ammo", "-400% extra large ammo when shooting with special ammo weapons. +12% Lucky Shot Chance for each extra ammo consumed in this shooting.", null, null),
        [("scroll", 5854, 2)] = new("Special Ammo", "-400% extra large ammo when shooting with special ammo weapons. +12% Lucky Shot Chance for each large ammo consumed in this shooting, +0.5x CritX for every special ammo consumed.", null, null),
        [("scroll", 5855, 2)] = new("Connected Mind", "When using the same ammo type with a teammate, ＋10% Weapon DMG; when using the same weapon type with a teammate, +10% Lucky Shot Chance; when using the same weapon with a teammate, +0.2x CritX.", null, null),
    };
}
